### PR TITLE
feat: added minimalist website

### PR DESCRIPTION
**Pull request by Mohasin-Haque**
<hr>

## Description 📜

I have added the minimalist fitness website in the templates. It is fully responsive. 

<hr>

# Gimps of Fitness-website
This is a fitness app
### CTA section
image
### Classes section
image
### Our story section
image

### Managed by 
* [Mohasin Haque](https://twitter.com/mohasin_haque)

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@Mohasin-Haque is it responsive ... can u add one small clip showing its responsiveness

**Comment by Mohasin-Haque** [comment]
The website is fully responsive 
image
image
image

**Comment by Mohasin-Haque** [comment]
@Ayan-thecodeking  please re review

**Comment by Ayan-thecodeking** [comment]
@Mohasin-Haque  Thnx for Contributing !! Hope you learned something new , Don't forget to star repo and follow me for further such amazing repos 👍

**Pull request merged**
