### PR TITLE
added new footer design

### PR DESCRIPTION
**Pull request by MananAgr2003**
Updated A New Footer Design On The Food Website.

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@MananAgr2003 dude add screen shots of your changes

**Comment by MananAgr2003** [comment]
Before:
prevFooter


After:
newFoot

**Comment by Ayan-thecodeking** [comment]
@MananAgr2003 kindly show me the responsiveness

**Comment by Ayan-thecodeking** [comment]
@MananAgr2003  Thnx for Contributing !! Hope you learned something new , Don't forget to star repo and follow me for further such amazing repos 👍

JUST do one thing add the Issue number and I'll merge ur PR

**Comment by MananAgr2003** [comment]
Hey! Kindly Check The Issue No. 123

**Comment by MananAgr2003** [comment]
Hey! Kindly Check The Issue No. 123

**Comment by MananAgr2003** [comment]
@Ayan-thecodeking

**Pull request merged**
