### PR TITLE
Fitnezz Template added

### PR DESCRIPTION
**Pull request by Subhradeep10**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## This would be great if you provide any of this   📝

- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Navbar design
- [x] Footer
- [x] Single page website
- [x] Animation design
- [x] parallax effect design 
- [x] Others

<hr>

## Checklist ✅

]
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Any tutorials or documentation have you added 
(made by you only not from google)
- [ ] Tutorial
- [x] Documentation

<hr>

## Screenshots / Gif (Compulsory) 📸

<hr>

### CODE REVIEW

**Comment by Subhradeep10** [comment]
Screenshot from 2021-10-01 12-19-47
)

**Comment by Ayan-thecodeking** [comment]
hey @Subhradeep10 pls improve it ...content is not visible clearly

**Review by Ayan-thecodeking — COMMENTED** [review]
improvement requiremnt

**Comment by Subhradeep10** [comment]
@Ayan-thecodeking Check it out, I have fixed it

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking Check it out, I have fixed it

Can you pls add a screen recording showing responsiveness ...for both of your changes

**Comment by Subhradeep10** [comment]
https://user-images.githubusercontent.com/70656957/135655975-c352610a-7844-4062-8443-405b4f17ecbe.mp4

@Ayan-thecodeking See it bro, start watching from 7-8 second

**Comment by Subhradeep10** [comment]
Screenshot from 2021-10-02 08-13-18

@Ayan-thecodeking The files are changed..

**Comment by Ayan-thecodeking** [comment]
@Subhradeep10 pls add a screen recording ... Ss u have added is not up to mark 
I think lot of improvement is required in ur fitness template ...

**Comment by Subhradeep10** [comment]
https://user-images.githubusercontent.com/70656957/135701808-bc4af510-02a9-4f90-baea-0833c172cece.mp4

@Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
Ok @Subhradeep10 now ok..I'll merge it soon :)

**Comment by Subhradeep10** [comment]
@Ayan-thecodeking Sure

**Pull request merged**
