### PR TITLE
added weather app

### PR DESCRIPTION
**Pull request by Tushar-2003**
<hr>

## Description 📜

I wanted to add a simple and working weather app template in this repo for HacktoberFest 2022 #124

<hr>

## This would be great if you provide any of this   📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Navbar design
- [ ] Footer
- [x] Single-page website
- [ ] Animation design
- [ ] parallax effect design 
- [x] Others

<hr>

## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Any tutorials or documentation have you added 
(made by you only not from google)
- [ ] Tutorial
- [x] Documentation

<hr>

## Screenshots / Gif (Compulsory) 📸

Screenshot (81)
Screenshot (82)

<hr>

### CODE REVIEW

**Comment by Tushar-2003** [comment]
@Ayan-thecodeking  moved to templates folder have a look

**Comment by Ayan-thecodeking** [comment]
@Tushar-2003  Thnx for Contributing !! Hope you learned something new , Don't forget to star repo and follow me for further such amazing repos 👍

**Comment by Tushar-2003** [comment]
@Ayan-thecodeking I am not sure why but its still showing not accepted 😕, can you close this issues if it's merged

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I am not sure why but its still showing not accepted 😕, can you close this issues if it's merged

now ?

**Comment by Tushar-2003** [comment]
Fixed now thanks😃

**Pull request merged**
