### PR TITLE
Added Email Collector Database Template

### PR DESCRIPTION
**Pull request by Chirantanbanik**
@Ayan-thecodeking Hey please look into this, if you find the template g2g then merge it. Thank you!

Here's how the template looks!

demo

### CODE REVIEW

**Comment by Chirantanbanik** [comment]
Hey @Ayan-thecodeking kindly look into the PR if you feel it's g2g then kindly merge it. If you feel something can be improved then let me know.
Thank you.

**Comment by Ayan-thecodeking** [comment]
@Chirantanbanik can you please share the deploy link or some more details

**Comment by Chirantanbanik** [comment]
Deployed link: https://heroic-seahorse-98b05d.netlify.app/

**Comment by Ayan-thecodeking** [comment]
@Chirantanbanik Thnx for Contributing !! Hope you learned something new , Don't forget to star repo and follow me for further such amazing repos 👍

**Pull request merged**
