### PR TITLE
Update Footer

### LINKED ISSUE #4: Footer for the Website
<hr>

## Description 📜

I would like to work on footer. I want to add this feature. Please suggest me the design/things to be added in the footer part. I am keen to work on this. 
Please assign me this task. 

<hr>

## Domain of Contribution 📊
- [x] Footer

## Any tutorials or Documentation are you going to add 

<hr>

### PR DESCRIPTION
**Pull request by pranshukas**
<hr>

## Description 📜

Added Footer Template according to the design suggested. Please review my PR and revert in case any changes need to be made. Any Suggestions and Feedbacks are Welcomed. 
I did not use any framework, the code is pure HTML and CSS. 
Fixes #4 

<hr>

## This would be great if you provide any of this   📝

- [x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Footer

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](Coders-Evoke-Community/Amazing-Frontend_Templates/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](Coders-Evoke-Community/Amazing-Frontend_Templates/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Screenshots / Gif (Compulsory) 📸

image

<hr>

### CODE REVIEW

**Comment by pranshukas** [comment]
@Ayan-thecodeking Please review my PR and revert in case any changes need to be made. I created the footer element in accordance to design given by you without using any frameworks, just pure HTML,CSS. 
I have also attached the screenshot of the footer element.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking Please review my PR and revert in case any changes need to be made. I created the footer element in accordance to design given by you without using any frameworks, just pure HTML,CSS. I have also attached the screenshot of the footer element.

Hey @pranshukas pls add screen recording ... showing responsiveness of atleast footer ....or if you want you can try for whole website

**Comment by pranshukas** [comment]
@Ayan-thecodeking 
How can I make commits now? It's showing resolve conflicts. You merged a PR that had some lines changes conflicting with mine. Should I create new PR or I there's another way ?

**Comment by pranshukas** [comment]
@Ayan-thecodeking Please check I have added the screen recording of my work. 

https://user-images.githubusercontent.com/58984074/135708709-aec37751-578c-42b0-8568-31eb78327798.mp4

**Comment by Ayan-thecodeking** [comment]
ok cool @pranshukas just resolve the conflicts ...
or if you will get any issues in resolving then do create another pr and close this

**Pull request closed without merging**
