### PR TITLE
Added responsiveness

### LINKED ISSUE #6: add Responsiveness in website

### PR DESCRIPTION
**Pull request by gunjan-g**
<hr>

## Description 📜
Added responsiveness to the website and added a toggle bar in navbar on small scnreen size
Fixes #6

<hr>

## This would be great if you provide any of this   📝

- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Navbar design
- [ ] Footer
- [x] Single page website
- [ ] Animation design
- [ ] parallax effect design 
- [ ] Others

<hr>

## Checklist ✅

]
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Any tutorials or documentation have you added 
(made by you only not from google)
- [ ] Tutorial
- [x] Documentation

<hr>

## Screenshots / Gif (Compulsory) 📸
image
<br/>

image

<hr>

### CODE REVIEW

**Comment by gunjan-g** [comment]
@Ayan-thecodeking please review the pr

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking please review the pr

hey @gunjan-g ...pls add menubar in right side and you have full website responsive including filter gallary 
do add screen recording after improving

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
improvement requirement

**Comment by gunjan-g** [comment]
> > @Ayan-thecodeking please review the pr
> 
> hey @gunjan-g ...pls add menubar in right side and you have full website responsive including filter gallary do add screen recording after improving

can you elaborate menubar

**Comment by Ayan-thecodeking** [comment]
> > > @Ayan-thecodeking please review the pr
> > 
> > 
> > hey @gunjan-g ...pls add menubar in right side and you have full website responsive including filter gallary do add screen recording after improving
> 
> can you elaborate menubar



> > > @Ayan-thecodeking please review the pr
> > 
> > 
> > hey @gunjan-g ...pls add menubar in right side and you have full website responsive including filter gallary do add screen recording after improving
> 
> can you elaborate menubar
Inked135602544-c740c133-9acd-4670-af1a-9b0d2b912b2b_LI
also resolve merge conflicts @gunjan-g ....don't forget to pull the repo

**Comment by Ayan-thecodeking** [comment]
?? r u working @gunjan-g

**Comment by gunjan-g** [comment]
> ?? r u working @gunjan-g

yes

**Comment by gunjan-g** [comment]
> ?? r u working @gunjan-g

No, you can unassign me and assign someone else

**Pull request closed without merging**
