### PR TITLE
Added PortFolio-Templates

### PR DESCRIPTION
**Pull request by ChandaniM**
<hr>

## Description 📜

Added portfolio-template #11 

<hr>

## Domain of Contribution 📊

- [ x] Navbar design
- [ x] Footer
- [x ]Single page website
- [x ] Animation design
- [ x] parallax effect design

<hr>

## Checklist ✅

]
- [x ] I have performed a self-review of my own code or work.
- [ x] My changes generates no new warnings.
- [x ] I'm **Hacktoberfest** contributor

<hr>

## Screenshots / Gif (Compulsory) 📸

<hr>

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
hey @Subhradeep10 add ss and screen recording for your templates

**Comment by ChandaniM** [comment]
@Ayan-thecodeking , it seems you tagged the wrong user. Also I've added screenshots in the screenshots folder.. Do I need to add  them somewhere else?

**Comment by Subhradeep10** [comment]
@Ayan-thecodeking I haven't did it yet..Check the Favicon that's my PR

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I haven't did it yet..Check the Favicon that's my PR

yup so sry for that

**Pull request closed without merging**
