### PR TITLE
Added weather WebApp template

### LINKED ISSUE #144: Weather WebApp Template
**Is your feature request related to a problem? Please describe.**
I would like to add a weather webapp template.

**Describe the solution you'd like**
The website will be built using html and css and will be responsive.

**Describe alternatives you've considered**
NA

**Additional context**

### PR DESCRIPTION
**Pull request by sshiwangi**
<hr>

## Description 📜

1. Added simple weather website template built using HTML and CSS.
2. The website is Responsive.
3. Also added readme file.
Fixes #144 

<hr>

## This would be great if you provide any of this   📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Single page website

<hr>

## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Any tutorials or documentation have you added 
(made by you only not from google)
- [x] Documentation

<hr>

## Screenshots / Gif (Compulsory) 📸
weatherwebapp

weatherwebapp2

## medium device

##small devices

<hr>

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@sshiwangi can you please add SS showing responsiveness

**Comment by sshiwangi** [comment]
> @sshiwangi can you please add SS showing responsiveness

Sure

**Comment by sshiwangi** [comment]
@Ayan-thecodeking added ss showing responsiveness. Kindly review.

**Comment by Ayan-thecodeking** [comment]
@sshiwangi  Thnx for Contributing !! Hope you learned something new , Don't forget to star repo and follow me for further such amazing repos 👍

**Pull request merged**
