### PR TITLE
Responsive cards

### LINKED ISSUE #9: A Responsive Card that could be multi purpose
**Is your feature request related to a problem? Please describe.**
A responsive Profile card or a simple card with some animation where an image and some kind of description can be included.

**Describe the solution you'd like**
Making this card functionality with some animations.

**Additional context**
This issue is open to suggestions from @Ayan-thecodeking or other admins.

### PR DESCRIPTION
**Pull request by riasenpai**
<hr>

## Description 📜

The responsive cards have been added.
Fixes #9 

<hr>

## This would be great if you provide any of this   📝

- [x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Others

<hr>

## Checklist ✅

]
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

[<hr>](
https://user-images.githubusercontent.com/67195436/135628131-7f9dcb20-355f-42fe-9c8c-7638d68f5431.mp4
)

<hr>

## Screenshots / Gif (Compulsory) 📸

<hr>

### CODE REVIEW

**Comment by riasenpai** [comment]
@Ayan-thecodeking Here is the first issue.

**Comment by Ayan-thecodeking** [comment]
@riasenpai can you add hover effects or animations on cards ...
That would look more cool

**Comment by riasenpai** [comment]
Hey I did a zoom in on hover and also added a commented code for rotation of the image. Additionally also used data-aos library. @Ayan-thecodeking

**Comment by riasenpai** [comment]
https://user-images.githubusercontent.com/67195436/135648705-85c7e619-df90-481a-b524-7e752af24831.mp4

Adding a screen recording as well and there is a commented code there too for rotation of the image too, data aos is also used.

**Comment by Ayan-thecodeking** [comment]
Thnx for contributing @riasenpai ...
Ur name confused me 🥲

**Pull request merged**
