### PR TITLE
My Pet's Website

### PR DESCRIPTION
**Pull request by its-harsshhh**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
<h2>I created a MyPets Website</h2>

<hr>

## This would be great if you provide any of this   📝

- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [x] Other (If you choose other, Please mention changes below) 
- [x] I provided screenshot of website

<hr>

## Domain of Contribution 📊

- [x] Navbar design
- [ ] Footer
- [x] Single page website
- [ ] Animation design
- [ ] parallax effect design 
- [ ] Others

<hr>

## Checklist ✅

]
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Any tutorials or documentation have you added 
(made by you only not from google)
- [ ] Tutorial
- [x] Documentation

<hr>

## Screenshots / Gif (Compulsory) 📸
Capture
<hr>

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@its-harsshhh when you have created this project ??

**Comment by its-harsshhh** [comment]
@Ayan-thecodeking i have created this project yesterday on 30 sept for hacktoberfest2022

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking i have created this project yesterday on 30 sept for hacktoberfest2022

Ok let me check it's Valid or not .. because this time hacktober is very strict .. make sure that there is no commit before 30th September .. 

Let me know ?

**Comment by its-harsshhh** [comment]
@Ayan-thecodeking yes, i havenot done any commit before 30 sept

**Pull request closed without merging**
