### PR TITLE
Tour Before Trip

### LINKED ISSUE #151: Tour Before Trip
Html, Css and JS project, with background video.

Screenshot (284)

Screenshot (283)

please assign this issue.

### PR DESCRIPTION
**Pull request by Asttttha**
<hr>

## Description 📜

Html, Css and JS project, with background video.

Fixes #151 
<hr>

## This would be great if you provide any of this   📝

- [x] Other 
i have added pictures and deployed link below.

<hr>

## Domain of Contribution 📊

- [x] Single page website

<hr>

## Checklist ✅

]
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm **Hacktoberfest** contributor

<hr>

## Screenshots / Gif (Compulsory) 📸

Link : https://asttttha.github.io/TBT-website/
Screenshot (284)

Screenshot (283)

<hr>

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@Asttttha can you please fix its navbar responsiveness

**Comment by Asttttha** [comment]
@Ayan-thecodeking check once

**Comment by Asttttha** [comment]
fixed responsiveness @Ayan-thecodeking 
WhatsApp Image 2022-10-20 at 6 10 54 PM

**Comment by Ayan-thecodeking** [comment]
good work @Asttttha ... thnx for contributing to this project

**Pull request merged**
